name: IndexNow Submission

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  indexnow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Submit URLs to IndexNow
        run: |
          echo "Gathering URLs from sitemap..."
          URLS=$(curl -s https://icanread.io/sitemap.xml | grep -o 'https://[^<]*' | sed 's/"//g')
          
          # Create JSON payload
          echo "Creating JSON payload..."
          JSON_PAYLOAD=$(cat << EOF
          {
            "host": "icanread.io",
            "key": "65cbd6f086194c549475b8650fa9dfc8",
            "keyLocation": "https://icanread.io/65cbd6f086194c549475b8650fa9dfc8.txt",
            "urlList": [$(echo "$URLS" | sed 's/^/"/;s/$/"/' | tr '\n' ',' | sed 's/,$//')]}
          EOF
          )
          
          echo "Submitting URLs to IndexNow..."
          curl -X POST "http://api.indexnow.org/IndexNow" \
            -H "Content-Type: application/json; charset=utf-8" \
            -H "Host: api.indexnow.org" \
            -d "$JSON_PAYLOAD"